### ISSUE TITLE
Milestone I

### ISSUE THREAD

**Issue by JiahangXu** [microsoft/nn-Meter#14]
- [x] Refine documentation
- [x] Check all copyright header
- [x] Add cache in the integration test
- [x] Check the bug that TorchConverter can not based on NNI
- [x] Check the bug that OnnxBasedTorchConverter differs in different torchvision version
- [x] benchmark dataset open-source
- [x] Check the incorrect kernel detection in NNIBasedTorchConverter (Jianyu)
- [ ] Pack a pip package for pip install
- [ ] Support nn-meter in nni 
    - [ ] Hardware-aware NAS
    - [ ] SPOS
    - [ ] Proxyless NAS
