### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by mydmdm** [microsoft/nn-Meter#20]
`nn-Meter` is not only a latency predictor but also a critical component in the hardware-aware model design. It empowers existing NAS (neural architecture search) and other efficient model design tasks to be specialized for the target hardware platform. 

There are multiple aspects will be covered in this and related repo, including:
- **latency prediction and pre-trained predictors**
  - the IR converter, kernel detection tools
  - builtin kernel predictors and pre-trained weights
- **algorithm integration** (mainly in [NNI](https://github.com/microsoft/nni)), the integration of latency prediction in existing NAS and compression algorithms.
- **model latency dataset**, the collected latencies of thousands of model architectures. Also includes data loaders and an improved GNN predictor.

### version 1.0-alpha
- Date: 2020 August
- Latency prediction
  - [x] basic framework and utilities for latency prediction (e.g., config management, artifacts downloading, builtin predictors)
  - [x] basic CI workflow with integrated test
  - [x] documentation and examples
- Algorithm integration
  - [x] initial multi-trial NAS example

### version 1.0-beta
- Date: 2020 September (TBD)
- Algorithm integration
  - [ ] SPOS / Proxyless NAS
- Dataset
  - [ ] make model-latency dataset public
  - [ ] reference design of an improved GNN latency predictor

**Comment by liuyibox** [comment]
Hi, I'm wondering if you would share your modification code to TFLite, which implements the GPU operator-level profiling?

**Comment by Lynazhang** [comment]
> Hi, I'm wondering if you would share your modification code to TFLite, which implements the GPU operator-level profiling?

Hi, @liuyibox, we will soon share a patch about the GPU operator-level profiling.
